[workspace]
resolver = "3"
members = ["crates/beskar-lines", "crates/beskar-core", "crates/beskar-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"
unused_must_use = "deny"

[workspace.lints.clippy]
dbg_macro = "warn"
todo = "warn"
unwrap_used = "warn"

[profile.release]
lto = true
codegen-units = 1
strip = true
