//! Migration from the legacy `skill-manager` Home (spec §120-§124, §136
//! Phase 6).
//!
//! `beskar migrate skm --home <path> [--registry <path>] [--dry-run]`
//! converts one legacy Home into a Beskar Library (in place, preserving the
//! skills' Git history and bucket layout) plus machine-local Registry
//! entries (§120).
//!
//! # Assumed legacy format (fixture contract)
//!
//! The legacy format is not fully specified; migration is implemented
//! against the following fixture format, built from §120-§124's vocabulary
//! and generated by `beskar_test_support::skm`:
//!
//! ```text
//! <home>/                          # the legacy skills Git repository
//! ├── .git/
//! ├── skills/<bucket...>/<name>/SKILL.md (+ regular files)
//! ├── profiles.json                # legacy Profile definitions (ordered)
//! └── registry.json                # legacy Installations: ONE profile each (§121)
//! ```
//!
//! `profiles.json`: `{"schema":1,"profiles":[{"name","description"?,"skills":[...]}]}`.
//! `registry.json`: `{"schema":1,"installations":[{"workspace","target",
//! "profile","source_ref"?,"commit"?,"installed_at"?,"library"?}]}` where
//! `source_ref` defaults to `main`, `commit` is the last applied library
//! commit (provenance only), `installed_at` is RFC 3339, and `library` is an
//! optional recorded source-repo identity used for §122 matching.
//!
//! Legacy stamps `.skm.json` inside installed skill directories:
//! `{"schema":1,"manager":"skm","skill","source_ref"?,"commit"?,
//! "files":{"<skill-relative path>":{"sha256","executable"}}}` (§124).
//!
//! # Conversion rules
//!
//! * Library: `beskar.toml` (fresh `library_id`, default_ref `main`) and
//!   `profiles/<name>.toml` are committed ON TOP of the existing history in
//!   one scoped commit (§72) — skill directories are untouched, so Git
//!   history and bucket layout are preserved by construction. A home that
//!   already contains `beskar.toml` is refused (already migrated).
//! * Profiles (§123): fresh UUIDs, same name, same skill order. Profiles
//!   referencing skills absent from the library still migrate but are
//!   reported `valid = false` with the missing skills listed (Beskar's own
//!   `profile validate`/`status` continue to surface them; dropping the
//!   references would destroy information, §4).
//! * Registry (§121, §122): each legacy entry becomes one Installation with
//!   exactly one attachment. Entries resolving to the same
//!   `(workspace, target)` merge into one Installation with several
//!   attachments ONLY when every entry agrees on the recorded `library`
//!   identity and the effective `source_ref`; exact duplicates (same
//!   profile AND ref) collapse silently. Any disagreement is reported as
//!   one typed [`Error::MigrationAmbiguity`] listing every conflict, and
//!   NOTHING is written (§122, §4: never guess).
//! * Stamps (§124): for each installed skill carrying `.skm.json`, the
//!   conversion to `.beskar.json` (without recopying) happens only when the
//!   mapping is fully confident: the skill exists exactly once at the
//!   installation's resolved source-ref commit, the legacy manifest covers
//!   exactly the committed file set, and every file's on-disk bytes, the
//!   legacy hash, and the committed blob hash agree (executable state
//!   included). The verified stamp is then written and the legacy stamp is
//!   removed (Beskar recognizes and owns both stamp names, §70). Otherwise
//!   NOTHING in the target is touched, the legacy stamp survives as
//!   unmanaged content, and the installation is reported
//!   `needs_reconciliation` (§124) — a plain `beskar update` afterwards
//!   installs/reconciles it safely. Stamps are only claimed for skills in
//!   the migrated desired membership; other target content stays unmanaged.
//! * Ordering of effects (§89, §61): plan fully (read-only) → write library
//!   metadata → re-validate → scoped commit → stamp conversions → Registry
//!   persisted LAST. Dry-run performs zero writes anywhere (§91).

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

use beskar_git::{GitBackend, SystemGitBackend, TreeEntryKind};

use crate::config::{DEFAULT_REF, LibraryConfig, PlatformDirs};
use crate::error::{Error, Result};
use crate::ids::{InstallationId, LibraryId, ProfileId, SkillName};
use crate::library::Library;
use crate::paths::{split_leaf, to_native_path, validate_bucket, validate_relative_path};
use crate::profile::{Profile, validate_profile_name};
use crate::registry::{
    Adapter, Installation, LastAppliedMembership, LastAppliedState, ProfileAttachment, Registry,
    RegistryStore, WorkspaceInfo,
};
use crate::skill::{SKILL_FILE, SkillFrontmatter};
use crate::stamp::{FILE_NAME as BESKAR_STAMP_FILE, Stamp};

/// The recognized legacy installation stamp file name (spec §124).
pub const SKM_STAMP_FILE: &str = ".skm.json";
/// The legacy profile-definition file inside the Home.
pub const SKM_PROFILES_FILE: &str = "profiles.json";
/// The default legacy registry file inside the Home (`--registry` overrides).
pub const SKM_REGISTRY_FILE: &str = "registry.json";
/// The legacy manager identifier in `.skm.json` (spec §124).
pub const SKM_MANAGER: &str = "skm";

/// The only legacy schema version this converter understands (§129: older
/// readers fail closed on unsupported schemas — the same applies here).
const SKM_SCHEMA: i64 = 1;

// ---- legacy document formats (fixture contract, see module docs) --------

/// One legacy registry entry: ONE profile per installation (spec §121).
#[derive(Debug, Clone, Deserialize)]
pub struct SkmEntry {
    /// Absolute workspace path.
    pub workspace: String,
    /// Workspace-relative target directory.
    pub target: String,
    /// The single legacy profile name.
    pub profile: String,
    /// Source ref; defaults to [`DEFAULT_REF`] when absent.
    #[serde(default)]
    pub source_ref: Option<String>,
    /// Last applied library commit (provenance only; never trusted).
    #[serde(default)]
    #[allow(dead_code)]
    pub commit: Option<String>,
    /// RFC 3339 attachment/installation time.
    #[serde(default, with = "time::serde::rfc3339::option")]
    pub installed_at: Option<OffsetDateTime>,
    /// Optional recorded source-repo identity (§122 matching).
    #[serde(default)]
    pub library: Option<String>,
}

/// One legacy profile definition (spec §123): name, optional description,
/// ordered skills.
#[derive(Debug, Clone, Deserialize)]
pub struct SkmProfile {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub skills: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
struct SkmRegistryFile {
    schema: i64,
    #[serde(default)]
    installations: Vec<SkmEntry>,
}

#[derive(Debug, Clone, Deserialize)]
struct SkmProfilesFile {
    schema: i64,
    #[serde(default)]
    profiles: Vec<SkmProfile>,
}

/// A legacy `.skm.json` payload (spec §124). Unknown extra fields are
/// ignored — the legacy format is not fully specified.
#[derive(Debug, Clone, Deserialize)]
struct SkmStamp {
    schema: i64,
    manager: String,
    skill: String,
    #[serde(default)]
    files: BTreeMap<String, SkmStampFile>,
}

#[derive(Debug, Clone, Deserialize)]
struct SkmStampFile {
    sha256: String,
    #[serde(default)]
    executable: bool,
}

// ---- serializable plan and outcome (§89, §91) ----------------------------

/// One migrated profile (§123): fresh UUID, same name, same skill order;
/// `valid = false` marks profiles referencing missing skills.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MigratedProfile {
    pub name: String,
    pub id: ProfileId,
    pub description: Option<String>,
    pub skills: Vec<SkillName>,
    /// Skills absent from the migrated library (§123: migrate anyway,
    /// marked invalid).
    pub missing_skills: Vec<SkillName>,
    pub valid: bool,
}

/// The planned stamp conversion for one installed skill (§124). `stamp_json`
/// is the fully verified `.beskar.json` payload; `legacy_stamp` records that
/// a `.skm.json` must be removed beside it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StampWrite {
    pub installation_id: InstallationId,
    /// Absolute directory of the installed skill.
    pub target_dir: PathBuf,
    pub skill: SkillName,
    pub stamp_json: String,
    pub legacy_stamp: bool,
}

/// Per-target migration report (§124 outcomes).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TargetMigrationReport {
    pub installation_id: InstallationId,
    pub workspace: PathBuf,
    pub target: String,
    /// Whether the installation's source ref resolved in the legacy repo.
    pub source_ref_resolved: bool,
    /// Legacy stamps confidently converted to `.beskar.json` (§124).
    pub converted: Vec<SkillName>,
    /// Legacy stamps that could NOT be mapped confidently (left untouched).
    pub unconverted: Vec<SkillName>,
    /// Desired skills with no installed directory (update will install).
    pub missing: Vec<SkillName>,
    /// Unmanaged target entries left exactly as found (§8.6, §20).
    pub unmanaged: Vec<String>,
    /// §124: at least one skill needs reinstall/reconciliation.
    pub needs_reconciliation: bool,
}

/// The complete, serializable migration plan (§89). Built entirely from
/// read-only inspection; execution applies exactly this plan.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MigrationPlan {
    /// The legacy Home (which becomes the Library root, §120).
    pub home: PathBuf,
    pub library_id: LibraryId,
    pub default_ref: String,
    pub commit_message: String,
    /// Library-relative paths the migration commit owns (§72).
    pub owned_paths: Vec<String>,
    pub profiles: Vec<MigratedProfile>,
    /// The Registry entries to persist, fully formed (§121, §122).
    pub installations: Vec<Installation>,
    pub targets: Vec<TargetMigrationReport>,
    /// Verified stamp conversions to apply after the library commit (§124).
    pub stamps: Vec<StampWrite>,
    /// Non-fatal advisories.
    pub warnings: Vec<String>,
}

impl MigrationPlan {
    /// Whether anything would be written at all.
    pub fn is_no_op(&self) -> bool {
        self.owned_paths.is_empty() && self.installations.is_empty() && self.stamps.is_empty()
    }
}

/// The result of one `beskar migrate skm` run.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MigrationOutcome {
    pub plan: MigrationPlan,
    pub dry_run: bool,
    pub executed: bool,
    /// The migration commit hash, when one was created (§72).
    pub library_commit: Option<String>,
    /// The Beskar Registry file the entries belong to (machine-local).
    pub registry_path: PathBuf,
    pub registry_written: bool,
}

/// `beskar migrate skm` arguments (§120). `registry` overrides the legacy
/// registry file location; when absent, `<home>/registry.json` is used.
#[derive(Debug, Clone)]
pub struct MigrateSkmRequest<'a> {
    pub home: &'a Path,
    pub registry: Option<&'a Path>,
    pub dry_run: bool,
}

/// The migration service: reads a legacy Home, plans the conversion, and on
/// execution applies it (§89). Holds only machine-local state — migration
/// never requires an active Beskar Library.
pub struct Migrator {
    dirs: PlatformDirs,
    backend: SystemGitBackend,
}

impl Migrator {
    /// Builds a migrator from explicit platform directories (§86; tests
    /// inject temp directories).
    pub fn new(dirs: PlatformDirs) -> Self {
        Self {
            dirs,
            backend: SystemGitBackend,
        }
    }

    /// Builds a migrator from process environment (`BESKAR_HOME`, §86).
    pub fn from_env() -> Self {
        Self::new(PlatformDirs::from_env())
    }

    /// Platform directories (the machine-local Registry target).
    pub fn dirs(&self) -> &PlatformDirs {
        &self.dirs
    }

    /// Converts a legacy skill-manager Home per §120-§124. On ambiguity the
    /// returned error is [`Error::MigrationAmbiguity`] and nothing is
    /// written; dry-runs perform zero writes (§91).
    pub fn migrate_skm(&self, request: MigrateSkmRequest<'_>) -> Result<MigrationOutcome> {
        let home = self.validate_home(request.home)?;
        let registry_path = match request.registry {
            Some(explicit) => {
                if !explicit.is_file() {
                    return Err(Error::config(format!(
                        "--registry file {} does not exist",
                        explicit.display()
                    )));
                }
                explicit.to_path_buf()
            }
            None => home.join(SKM_REGISTRY_FILE),
        };
        let profiles = read_profiles_file(&home.join(SKM_PROFILES_FILE))?;
        let entries = read_registry_file(&registry_path)?;

        // The entire plan is read-only; every refusal below happens before
        // any write (§89, §122).
        let plan = self.build_plan(&home, profiles, entries)?;

        if request.dry_run || plan.is_no_op() {
            return Ok(MigrationOutcome {
                plan,
                dry_run: request.dry_run,
                executed: false,
                library_commit: None,
                registry_path: RegistryStore::from_dirs(&self.dirs).path().to_path_buf(),
                registry_written: false,
            });
        }
        self.execute(plan)
    }

    // ---- planning (read-only, §89 steps 1-3) -----------------------------

    fn validate_home(&self, home: &Path) -> Result<PathBuf> {
        if !home.is_dir() {
            return Err(Error::config(format!(
                "skill-manager home {} does not exist or is not a directory",
                home.display()
            )));
        }
        if home.join(crate::library::CONFIG_FILE).exists() {
            return Err(Error::validation(format!(
                "{} already contains beskar.toml — it is already a Beskar \
                 Library; migration was applied before or is unnecessary",
                home.display()
            )));
        }
        if !home.join(".git").exists() {
            return Err(Error::library(format!(
                "{} is not a Git repository — skill Git history cannot be \
                 preserved without one (§120)",
                home.display()
            )));
        }
        if !home.join("skills").is_dir() {
            return Err(Error::library(format!(
                "{} has no skills/ directory — not a recognizable \
                 skill-manager home",
                home.display()
            )));
        }
        // Refuse to migrate into a collision (§4: safer behavior).
        if home.join("profiles").exists() {
            return Err(Error::validation(format!(
                "{} already contains a profiles/ directory — remove or rename \
                 it before migrating",
                home.display()
            )));
        }
        Ok(home.to_path_buf())
    }

    fn build_plan(
        &self,
        home: &Path,
        profiles: Vec<SkmProfile>,
        entries: Vec<SkmEntry>,
    ) -> Result<MigrationPlan> {
        let skills_root = home.join("skills");
        let available = validate_skills_working_tree(&skills_root, "skills")?;

        // Profiles: fresh UUIDs, same names, same order (§123). Shape
        // problems are fatal and all reported together; missing referenced
        // skills only mark the profile invalid (§123).
        let mut shape_problems: Vec<String> = Vec::new();
        let mut seen_names: BTreeSet<String> = BTreeSet::new();
        let mut profile_map: BTreeMap<String, Profile> = BTreeMap::new();
        let mut migrated_profiles: Vec<MigratedProfile> = Vec::new();
        for legacy in &profiles {
            if let Err(err) = validate_profile_name(&legacy.name) {
                shape_problems.push(format!("profile {:?}: {err}", legacy.name));
                continue;
            }
            if !seen_names.insert(legacy.name.clone()) {
                shape_problems.push(format!(
                    "profile {:?} is defined more than once in {SKM_PROFILES_FILE}",
                    legacy.name
                ));
                continue;
            }
            let mut skills = Vec::new();
            let mut listed: BTreeSet<String> = BTreeSet::new();
            for raw in &legacy.skills {
                match SkillName::parse(raw) {
                    Ok(name) => {
                        if !listed.insert(name.as_str().to_owned()) {
                            shape_problems.push(format!(
                                "profile {:?} lists skill {name} more than once",
                                legacy.name
                            ));
                            continue;
                        }
                        skills.push(name);
                    }
                    Err(err) => shape_problems.push(format!(
                        "profile {:?} references unrepresentable skill name: {err}",
                        legacy.name
                    )),
                }
            }
            let missing: Vec<SkillName> = skills
                .iter()
                .filter(|skill| !available.contains_key(skill))
                .cloned()
                .collect();
            let profile = Profile {
                schema: crate::profile::SCHEMA,
                id: ProfileId::generate(),
                name: legacy.name.clone(),
                description: legacy.description.clone(),
                skills: skills.clone(),
            };
            migrated_profiles.push(MigratedProfile {
                name: legacy.name.clone(),
                id: profile.id,
                description: legacy.description.clone(),
                missing_skills: missing.clone(),
                valid: missing.is_empty(),
                skills,
            });
            profile_map.insert(legacy.name.clone(), profile);
        }
        if !shape_problems.is_empty() {
            return Err(Error::validation(format!(
                "legacy profiles cannot be converted; fix {SKM_PROFILES_FILE} \
                 and re-run: {}",
                shape_problems.join("; ")
            )));
        }

        // Registry entries: validate shape, then group by (workspace,
        // target) for §121/§122 conversion.
        let mut groups: Vec<InstallationGroup> = Vec::new();
        let mut ambiguities: Vec<String> = Vec::new();
        for (index, entry) in entries.iter().enumerate() {
            if let Err(err) = validate_relative_path(&entry.target) {
                return Err(Error::validation(format!(
                    "legacy registry entry {index}: invalid target {:?}: {err}",
                    entry.target
                )));
            }
            let workspace = normalize_workspace(&entry.workspace).map_err(|err| {
                Error::validation(format!("legacy registry entry {index}: {err}"))
            })?;
            if !profile_map.contains_key(&entry.profile) {
                ambiguities.push(format!(
                    "entry {index} ({}) references profile {:?} which \
                     {SKM_PROFILES_FILE} does not define — restore the profile \
                     definition or remove the registration",
                    entry.workspace, entry.profile
                ));
            }
            let target = entry.target.clone();
            let group = match groups
                .iter_mut()
                .find(|g| g.target == target && g.workspace == workspace)
            {
                Some(group) => group,
                None => {
                    groups.push(InstallationGroup {
                        workspace,
                        target,
                        entries: Vec::new(),
                    });
                    groups.last_mut().expect("just pushed")
                }
            };
            group.entries.push((index, entry.clone()));
        }

        // §122 merge evaluation. Exact duplicates collapse; everything else
        // that disagrees is ambiguity, reported in one pass.
        for group in &groups {
            let mut refs: BTreeSet<&str> = BTreeSet::new();
            for (_, entry) in &group.entries {
                refs.insert(entry.source_ref.as_deref().unwrap_or(DEFAULT_REF));
            }
            if refs.len() > 1 {
                let mut joined: Vec<&str> = refs.into_iter().collect();
                joined.sort_unstable();
                ambiguities.push(format!(
                    "{} ({}) has registrations with differing source refs \
                     ({}) — one Installation resolves exactly one ref (§122, \
                     §135.17); separate targets or explicit registry edits \
                     are required",
                    group.workspace.display(),
                    group.target,
                    joined.join(", ")
                ));
            }
            let recorded: BTreeSet<&str> = group
                .entries
                .iter()
                .filter_map(|(_, entry)| entry.library.as_deref())
                .collect();
            if recorded.len() > 1 {
                let mut joined: Vec<String> = recorded.iter().map(|s| (*s).to_owned()).collect();
                joined.sort();
                ambiguities.push(format!(
                    "{} ({}) has registrations recorded against different \
                     library identities ({}) — they may not originate from \
                     this home's skills repository (§122)",
                    group.workspace.display(),
                    group.target,
                    joined.join(", ")
                ));
            }
        }
        if !ambiguities.is_empty() {
            return Err(Error::migration_ambiguity(format!(
                "{} legacy registration problem(s); nothing was written:\n - {}",
                ambiguities.len(),
                ambiguities.join("\n - ")
            )));
        }

        // Resolve each distinct source ref against the legacy repository
        // (committed state is authoritative, §8.1). An unresolvable ref is
        // not fatal: the registration migrates and is marked for
        // reconciliation (§38 Missing-ref, §124).
        let mut resolved: BTreeMap<String, Option<String>> = BTreeMap::new();
        for group in &groups {
            let reference = group.source_ref().to_owned();
            resolved
                .entry(reference)
                .or_insert_with(|| self.backend.resolve_ref(home, group.source_ref()).ok());
        }

        // Build the plan pieces.
        let library_id = LibraryId::generate();
        let config = LibraryConfig::new(library_id);
        let mut owned_paths = vec![crate::library::CONFIG_FILE.to_owned()];
        let mut warnings: Vec<String> = Vec::new();
        let mut installations: Vec<Installation> = Vec::new();
        let mut targets: Vec<TargetMigrationReport> = Vec::new();
        let mut stamps: Vec<StampWrite> = Vec::new();
        let now = OffsetDateTime::now_utc();

        for profile in &migrated_profiles {
            owned_paths.push(format!("profiles/{}.toml", profile.name));
        }

        for group in &groups {
            let reference = group.source_ref().to_owned();
            let resolved_commit = resolved.get(&reference).cloned().flatten();
            // Attachments in §17 order: legacy installation time, then
            // registry file order.
            let mut ordered: Vec<(usize, SkmEntry)> = group.entries.clone();
            ordered.sort_by_key(|(index, entry)| (entry.installed_at, *index));
            let mut attachments: Vec<ProfileAttachment> = Vec::new();
            let mut profile_ids: Vec<ProfileId> = Vec::new();
            let mut seen_profiles: BTreeSet<String> = BTreeSet::new();
            for (_, entry) in ordered {
                // The ambiguity pass guarantees the profile exists and that
                // each (profile, ref) pair is unique within the group, so
                // the first occurrence of a profile is the only one.
                if !seen_profiles.insert(entry.profile.clone()) {
                    continue;
                }
                let profile = &profile_map[&entry.profile];
                profile_ids.push(profile.id);
                attachments.push(ProfileAttachment {
                    id: profile.id,
                    name: profile.name.clone(),
                    attached_at: entry.installed_at.unwrap_or(now),
                });
            }

            // Desired membership: union of the attached profiles' skills
            // (§10, §36), remembering which profiles require what.
            let mut desired: BTreeMap<SkillName, Vec<ProfileId>> = BTreeMap::new();
            for profile in profile_map.values() {
                if !profile_ids.contains(&profile.id) {
                    continue;
                }
                for skill in &profile.skills {
                    desired.entry(skill.clone()).or_default().push(profile.id);
                }
            }

            let installation_id = InstallationId::generate();
            let installation = Installation {
                id: installation_id,
                library_id,
                workspace: group.workspace.clone(),
                target: group.target.clone(),
                adapter: adapter_for(&group.target),
                source_ref: reference.clone(),
                profiles: attachments,
                last_applied: match &resolved_commit {
                    Some(commit) => LastAppliedState {
                        source_commit: Some(commit.clone()),
                        profile_commits: profile_ids
                            .iter()
                            .map(|id| (*id, commit.clone()))
                            .collect(),
                        skill_membership: LastAppliedMembership {
                            skill_profiles: desired.clone(),
                        },
                    },
                    // An unresolvable ref claims nothing (§38 Missing-ref).
                    None => LastAppliedState::default(),
                },
                workspace_info: detect_workspace_info(&self.backend, &group.workspace),
                installed_at: now,
                updated_at: now,
            };

            // §124 stamp conversion for the skills this installation owns.
            let mut report = TargetMigrationReport {
                installation_id,
                workspace: group.workspace.clone(),
                target: group.target.clone(),
                source_ref_resolved: resolved_commit.is_some(),
                converted: Vec::new(),
                unconverted: Vec::new(),
                missing: Vec::new(),
                unmanaged: Vec::new(),
                needs_reconciliation: false,
            };
            match resolved_commit.as_deref() {
                Some(commit) => {
                    let context = StampContext {
                        backend: &self.backend,
                        repo: home,
                        commit,
                        source_ref: &reference,
                        installation: &installation,
                        library_id,
                    };
                    convert_target_stamps(
                        &context,
                        &desired,
                        &mut report,
                        &mut stamps,
                        &mut warnings,
                    );
                }
                None => {
                    report.needs_reconciliation = true;
                    warnings.push(format!(
                        "{} ({}) uses source ref {reference:?} which does not \
                         resolve in the legacy repository — no stamps could \
                         be converted; run `beskar update` after fixing the \
                         ref (§38 Missing-ref, §124)",
                        group.workspace.display(),
                        group.target
                    ));
                    collect_target_entries(&group.workspace, &group.target, &desired, &mut report);
                }
            }
            installations.push(installation);
            targets.push(report);
        }

        // Refuse to clobber an existing machine-local Registry ownership
        // (§26: two Installations MUST NOT own the same target).
        let store = RegistryStore::from_dirs(&self.dirs);
        let existing = store.load()?;
        for installation in &installations {
            for other in &existing.installations {
                if other.target == installation.target
                    && same_workspace(&other.workspace, &installation.workspace)
                {
                    return Err(Error::registry(format!(
                        "the Beskar registry already has installation {} for \
                         {} ({}); migrate would duplicate it — remove or \
                         unregister the existing installation first (§26)",
                        other.id,
                        installation.workspace.display(),
                        installation.target
                    )));
                }
            }
        }

        owned_paths.sort();
        owned_paths.dedup();
        Ok(MigrationPlan {
            home: home.to_path_buf(),
            library_id,
            default_ref: config.default_ref.clone(),
            commit_message: "beskar: migrate from skill-manager".to_owned(),
            owned_paths,
            profiles: migrated_profiles,
            installations,
            targets,
            stamps,
            warnings,
        })
    }

    // ---- execution (§89 steps 4-5, §61) ----------------------------------

    fn execute(&self, plan: MigrationPlan) -> Result<MigrationOutcome> {
        let store = RegistryStore::from_dirs(&self.dirs);
        // The advisory library lock covers the mutating phase (§88); the
        // migrated repository is the library being mutated.
        let _library_lock =
            crate::lock::lock_file_exclusive(&self.dirs.state_dir.join("library.lock"), "library")?;

        // 1. Library metadata: beskar.toml + profiles/<name>.toml. The
        // profiles directory always exists (§9 structure), even when the
        // legacy home defined none.
        let mut config = LibraryConfig::new(plan.library_id);
        config.default_ref = plan.default_ref.clone();
        write_owned_file(
            plan.home.join(crate::library::CONFIG_FILE),
            &config.to_toml()?,
        )?;
        std::fs::create_dir_all(plan.home.join(&config.profiles_dir))?;
        for profile in &plan.profiles {
            let full = Profile {
                schema: crate::profile::SCHEMA,
                id: profile.id,
                name: profile.name.clone(),
                description: profile.description.clone(),
                skills: profile.skills.clone(),
            };
            let relative = format!("profiles/{}.toml", profile.name);
            write_owned_file(plan.home.join(to_native_path(&relative)), &full.to_toml()?)?;
        }

        // 2. The complete result must validate before the commit (§74).
        let library = Library::open_at(&plan.home)?;
        library.scan().map_err(|err| {
            Error::library(format!(
                "the migrated library is invalid; the working tree holds \
                 uncommitted metadata — inspect {} and revert manually ({err})",
                plan.home.display()
            ))
        })?;

        // 3. One scoped commit on top of the preserved history (§72, §120).
        let commit =
            self.backend
                .commit_paths(&plan.home, &plan.commit_message, &plan.owned_paths)?;

        // 4. Stamp conversions (§124): write the verified `.beskar.json`,
        // remove the legacy `.skm.json`. Targets are not committed anywhere.
        for stamp in &plan.stamps {
            std::fs::create_dir_all(&stamp.target_dir)?;
            std::fs::write(stamp.target_dir.join(BESKAR_STAMP_FILE), &stamp.stamp_json)?;
            if stamp.legacy_stamp {
                let legacy = stamp.target_dir.join(SKM_STAMP_FILE);
                if legacy.exists() {
                    std::fs::remove_file(&legacy)?;
                }
            }
        }

        // 5. Registry persisted LAST (§61, §29).
        let mut registry: Registry = store.load()?;
        for installation in plan.installations.clone() {
            registry.insert(installation)?;
        }
        let lock = store.lock_exclusive()?;
        store.save_with_lock(&registry, &lock)?;

        Ok(MigrationOutcome {
            dry_run: false,
            executed: true,
            library_commit: commit,
            registry_path: store.path().to_path_buf(),
            registry_written: true,
            plan,
        })
    }
}

// ---- internal helpers ------------------------------------------------------

/// One `(workspace, target)` group of legacy entries (§121, §122).
struct InstallationGroup {
    workspace: PathBuf,
    target: String,
    entries: Vec<(usize, SkmEntry)>,
}

impl InstallationGroup {
    /// The group's effective source ref (§122: must be uniform to merge).
    fn source_ref(&self) -> &str {
        self.entries
            .first()
            .map(|(_, entry)| entry.source_ref.as_deref().unwrap_or(DEFAULT_REF))
            .unwrap_or(DEFAULT_REF)
    }
}

/// Reads `profiles.json`; a missing file means the home defines no profiles.
fn read_profiles_file(path: &Path) -> Result<Vec<SkmProfile>> {
    match std::fs::read_to_string(path) {
        Ok(raw) => {
            let file: SkmProfilesFile = serde_json::from_str(&raw).map_err(|e| {
                Error::schema(format!(
                    "{} is not a valid legacy profiles file: {e}",
                    path.display()
                ))
            })?;
            if file.schema != SKM_SCHEMA {
                return Err(Error::schema(format!(
                    "unsupported legacy profiles schema {} in {} (supported: \
                     {SKM_SCHEMA})",
                    file.schema,
                    path.display()
                )));
            }
            Ok(file.profiles)
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Vec::new()),
        Err(e) => Err(Error::Io(e)),
    }
}

/// Reads the legacy registry; a missing default file means no registrations.
fn read_registry_file(path: &Path) -> Result<Vec<SkmEntry>> {
    match std::fs::read_to_string(path) {
        Ok(raw) => {
            let file: SkmRegistryFile = serde_json::from_str(&raw).map_err(|e| {
                Error::registry(format!(
                    "{} is not a valid legacy registry file: {e}",
                    path.display()
                ))
            })?;
            if file.schema != SKM_SCHEMA {
                return Err(Error::schema(format!(
                    "unsupported legacy registry schema {} in {} (supported: \
                     {SKM_SCHEMA})",
                    file.schema,
                    path.display()
                )));
            }
            Ok(file.installations)
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Vec::new()),
        Err(e) => Err(Error::Io(e)),
    }
}

/// Validates every skill in the legacy working tree exactly as a Beskar
/// library scan will (§11-§13): frontmatter, leaf equality, global name
/// uniqueness, portable buckets, no special filesystem objects.
fn validate_skills_working_tree(
    skills_root: &Path,
    skills_dir_name: &str,
) -> Result<BTreeMap<SkillName, String>> {
    let mut roots: Vec<String> = Vec::new();
    for entry in walkdir::WalkDir::new(skills_root).follow_links(false) {
        let entry = entry.map_err(|e| Error::library(format!("scan failed: {e}")))?;
        let file_type = entry.file_type();
        if file_type.is_symlink() {
            return Err(Error::path_safety(format!(
                "symlinks are not allowed inside the Library: {} (§12)",
                entry.path().display()
            )));
        }
        if !file_type.is_file() && !file_type.is_dir() {
            return Err(Error::path_safety(format!(
                "special filesystem object is not allowed: {} (§12)",
                entry.path().display()
            )));
        }
        if !file_type.is_file() || entry.file_name() != std::ffi::OsStr::new(SKILL_FILE) {
            continue;
        }
        let parent = entry
            .path()
            .parent()
            .ok_or_else(|| Error::path_safety("SKILL.md without a parent"))?;
        if parent == skills_root {
            return Err(Error::validation(format!(
                "SKILL.md directly inside the skills directory is not a valid \
                 skill layout: {}",
                entry.path().display()
            )));
        }
        let relative = crate::paths::to_slash_path(
            parent
                .strip_prefix(skills_root)
                .map_err(|_| Error::path_safety("skill root escaped skills dir"))?,
        )?;
        roots.push(format!("{skills_dir_name}/{relative}"));
    }

    let mut sorted = roots.clone();
    sorted.sort();
    for (i, root) in sorted.iter().enumerate() {
        for other in &sorted[i + 1..] {
            if other.starts_with(&format!("{root}/")) {
                return Err(Error::validation(format!(
                    "nested skill directories are ambiguous: {other} lies \
                     inside {root}"
                )));
            }
        }
    }

    let mut skills = BTreeMap::new();
    for root in &roots {
        let (parent, leaf) = split_leaf(root);
        let prefix = format!("{skills_dir_name}/");
        let bucket = parent.strip_prefix(&prefix).unwrap_or_default();
        validate_bucket(bucket)?;
        let skill_path = skills_root
            .join(to_native_path(&root[prefix.len()..]))
            .join(SKILL_FILE);
        let bytes = std::fs::read(&skill_path)?;
        let frontmatter = SkillFrontmatter::parse_bytes(&bytes)?;
        if leaf != frontmatter.name.as_str() {
            return Err(Error::validation(format!(
                "directory leaf {leaf:?} does not equal skill name {:?} (§11)",
                frontmatter.name.as_str()
            )));
        }
        if skills
            .insert(frontmatter.name.clone(), root.clone())
            .is_some()
        {
            return Err(Error::validation(format!(
                "duplicate skill name {leaf:?}: skill names are globally \
                 unique within one Library revision regardless of bucket (§8.2)"
            )));
        }
    }
    Ok(skills)
}

/// Normalizes a legacy workspace path: must be absolute; canonicalized when
/// the directory exists so §122 grouping and §26 conflict checks compare
/// true paths, not spellings.
fn normalize_workspace(raw: &str) -> Result<PathBuf> {
    let path = PathBuf::from(raw);
    if !path.is_absolute() {
        return Err(Error::validation(format!(
            "legacy workspace path {raw:?} is not absolute — registry entries \
             must record absolute workspace paths"
        )));
    }
    Ok(path.canonicalize().unwrap_or(path))
}

/// §26 workspace equality tolerant of spelling/symlink differences.
fn same_workspace(a: &Path, b: &Path) -> bool {
    if a == b {
        return true;
    }
    match (a.canonicalize(), b.canonicalize()) {
        (Ok(ca), Ok(cb)) => ca == cb,
        (Ok(ca), Err(_)) => ca == b,
        (Err(_), Ok(cb)) => a == cb,
        (Err(_), Err(_)) => false,
    }
}

fn adapter_for(target: &str) -> Adapter {
    match target {
        ".agents/skills" => Adapter::Agents,
        ".claude/skills" => Adapter::Claude,
        _ => Adapter::Custom,
    }
}

/// Best-effort §30 repair metadata for the workspace's own Git repository.
fn detect_workspace_info(backend: &SystemGitBackend, workspace: &Path) -> Option<WorkspaceInfo> {
    if !workspace.is_dir() {
        return None;
    }
    let root = beskar_git::discover_repo(workspace).ok().flatten();
    let origin_url = root
        .as_deref()
        .and_then(|repo| backend.remote_url(repo, "origin").ok().flatten());
    let head = root
        .as_deref()
        .and_then(|repo| backend.resolve_ref(repo, "HEAD").ok());
    if root.is_none() && origin_url.is_none() && head.is_none() {
        return None;
    }
    Some(WorkspaceInfo {
        git_root: root,
        origin_url,
        head_at_registration: head,
    })
}

/// Writes one migration-owned library file (parents created).
fn write_owned_file(path: PathBuf, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;
    Ok(())
}

/// Collects unmanaged target entries (anything not claimed by the desired
/// membership) without touching them.
fn collect_target_entries(
    workspace: &Path,
    target: &str,
    desired: &BTreeMap<SkillName, Vec<ProfileId>>,
    report: &mut TargetMigrationReport,
) {
    let target_dir = workspace.join(to_native_path(target));
    let entries = match std::fs::read_dir(&target_dir) {
        Ok(entries) => entries,
        Err(_) => return,
    };
    for entry in entries.filter_map(std::result::Result::ok) {
        let name = entry.file_name().to_string_lossy().into_owned();
        let parsed = SkillName::parse(&name).ok();
        let is_desired_skill_dir = entry.file_type().map(|t| t.is_dir()).unwrap_or(false)
            && parsed.is_some_and(|skill| desired.contains_key(&skill));
        if !is_desired_skill_dir {
            report.unmanaged.push(name);
        }
    }
}

/// Identity context for §124 stamp conversion: where the committed truth
/// lives (backend, repo, resolved commit) and what claims the result
/// (installation, library).
struct StampContext<'a> {
    backend: &'a SystemGitBackend,
    repo: &'a Path,
    commit: &'a str,
    source_ref: &'a str,
    installation: &'a Installation,
    library_id: LibraryId,
}

/// §124 conversion for one installation target. Best-effort per skill: any
/// failed confidence check downgrades that skill to "needs reconciliation"
/// and never touches the target.
fn convert_target_stamps(
    context: &StampContext<'_>,
    desired: &BTreeMap<SkillName, Vec<ProfileId>>,
    report: &mut TargetMigrationReport,
    stamps: &mut Vec<StampWrite>,
    warnings: &mut Vec<String>,
) {
    let installation = context.installation;
    let target_dir = installation
        .workspace
        .join(to_native_path(&installation.target));

    // Desired skills with no directory cannot be verified (§124: mark for
    // reconciliation; a later `beskar update` installs them).
    let claimed: Vec<SkillName> = desired
        .keys()
        .filter(|skill| {
            let dir = target_dir.join(to_native_path(skill.as_str()));
            if dir.is_dir() {
                true
            } else {
                report.missing.push((*skill).clone());
                report.needs_reconciliation = true;
                false
            }
        })
        .cloned()
        .collect();

    for skill in claimed {
        let dir = target_dir.join(to_native_path(skill.as_str()));
        let legacy_path = dir.join(SKM_STAMP_FILE);
        let beskar_present = dir.join(BESKAR_STAMP_FILE).exists();
        if !legacy_path.is_file() {
            // No recorded legacy identity → nothing can be mapped
            // confidently; leave untouched and reconcile later.
            report.unmanaged.push(if beskar_present {
                format!("{} (already carries {BESKAR_STAMP_FILE})", skill.as_str())
            } else {
                format!("{} (unstamped)", skill.as_str())
            });
            report.needs_reconciliation = true;
            continue;
        }
        if beskar_present {
            warnings.push(format!(
                "{} already contains {BESKAR_STAMP_FILE}; migration left it \
                 untouched — inspect with `beskar status`",
                dir.display()
            ));
            report.unconverted.push(skill);
            report.needs_reconciliation = true;
            continue;
        }
        let outcome = std::fs::read_to_string(&legacy_path)
            .map_err(|e| format!("legacy stamp is unreadable: {e}"))
            .and_then(|raw| convert_one_stamp(context, &skill, &dir, &raw));
        match outcome {
            Ok(stamp_json) => {
                stamps.push(StampWrite {
                    installation_id: installation.id,
                    target_dir: dir,
                    skill: skill.clone(),
                    stamp_json,
                    legacy_stamp: true,
                });
                report.converted.push(skill);
            }
            Err(reason) => {
                warnings.push(format!(
                    "{}: legacy stamp not converted ({reason}) — the \
                     installation is marked for reconciliation (§124)",
                    dir.display()
                ));
                report.unconverted.push(skill);
                report.needs_reconciliation = true;
            }
        }
    }

    // Anything else in the target stays exactly as found.
    collect_target_entries(
        &installation.workspace,
        &installation.target,
        desired,
        report,
    );
}

/// Verifies one legacy stamp against committed state (§124) and returns the
/// `.beskar.json` payload, or the reason it could not be mapped confidently.
fn convert_one_stamp(
    context: &StampContext<'_>,
    skill: &SkillName,
    dir: &Path,
    raw: &str,
) -> std::result::Result<String, String> {
    let backend = context.backend;
    let repo = context.repo;
    let commit = context.commit;
    let legacy: SkmStamp =
        serde_json::from_str(raw).map_err(|e| format!("not a recognizable legacy stamp: {e}"))?;
    if legacy.schema != SKM_SCHEMA {
        return Err(format!(
            "unsupported legacy stamp schema {} (supported: {SKM_SCHEMA})",
            legacy.schema
        ));
    }
    if legacy.manager != SKM_MANAGER {
        return Err(format!(
            "unsupported legacy stamp manager {:?} (supported: {SKM_MANAGER})",
            legacy.manager
        ));
    }
    if legacy.skill != skill.as_str() {
        return Err(format!(
            "stamp claims skill {:?} but the directory is {skill}",
            legacy.skill
        ));
    }
    let committed = find_committed_skill(backend, repo, commit, skill)
        .map_err(|e| format!("committed state unreadable: {e}"))?
        .ok_or_else(|| format!("skill {skill} not found exactly once at {commit}"))?;

    // The legacy manifest must cover exactly the committed file set: a
    // Beskar stamp claims whole files, and anything else would silently
    // reclassify content as extra.
    let committed_files: BTreeSet<&str> = committed.files.keys().map(String::as_str).collect();
    let manifest_files: BTreeSet<&str> = legacy.files.keys().map(String::as_str).collect();
    if committed_files != manifest_files {
        let missing: Vec<&str> = committed_files
            .difference(&manifest_files)
            .copied()
            .collect();
        let extra: Vec<&str> = manifest_files
            .difference(&committed_files)
            .copied()
            .collect();
        return Err(format!(
            "manifest does not match the committed file set (missing: \
             {missing:?}, untracked: {extra:?})"
        ));
    }

    let mut verified: Vec<(&str, Vec<u8>, bool)> = Vec::new();
    for (relative, file) in &committed.files {
        let bytes = backend
            .blob(repo, commit, &file.path)
            .map_err(|e| format!("cannot read committed blob {:?}: {e}", file.path))?;
        let hash = crate::stamp::sha256_hex(&bytes);
        let recorded = legacy
            .files
            .get(relative)
            .map(|f| f.sha256.clone())
            .unwrap_or_default();
        if !hash.eq_ignore_ascii_case(&recorded) {
            return Err(format!(
                "{relative:?} hash differs between the legacy stamp and commit \
                 {commit}"
            ));
        }
        let legacy_executable = legacy
            .files
            .get(relative)
            .map(|f| f.executable)
            .unwrap_or(false);
        if file.executable != legacy_executable {
            return Err(format!(
                "{relative:?} executable state differs between the legacy \
                 stamp and commit {commit}"
            ));
        }
        let on_disk = dir.join(to_native_path(relative));
        let disk_bytes = std::fs::read(&on_disk)
            .map_err(|e| format!("installed file {} is unreadable: {e}", on_disk.display()))?;
        if crate::stamp::sha256_hex(&disk_bytes) != hash {
            return Err(format!(
                "installed {relative:?} differs from the committed bytes — \
                 local modification (§8.5)"
            ));
        }
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&on_disk)
                .map_err(|e| format!("cannot stat {}: {e}", on_disk.display()))?
                .permissions()
                .mode();
            if (mode & 0o111 != 0) != file.executable {
                return Err(format!(
                    "installed {relative:?} executable state differs from the \
                     committed mode (§34)"
                ));
            }
        }
        verified.push((relative, bytes, file.executable));
    }

    let skill_commit = backend
        .last_commit_touching(repo, commit, &committed.root)
        .ok()
        .flatten()
        .unwrap_or_else(|| commit.to_owned());
    let stamp = Stamp::build(
        context.installation.id,
        context.library_id,
        skill.clone(),
        context.source_ref,
        commit,
        skill_commit,
        verified.iter().map(|(p, b, e)| (*p, b.as_slice(), *e)),
    )
    .map_err(|e| format!("verified stamp rejected: {e}"))?;
    stamp.to_json().map_err(|e| e.to_string())
}

/// One committed skill at an exact revision: its root path and committed
/// files (skill-relative path -> repo-relative path + executable mode).
struct CommittedSkill {
    root: String,
    files: BTreeMap<String, CommittedFile>,
}

struct CommittedFile {
    path: String,
    executable: bool,
}

/// Locates the skill's committed directory under `skills/` at `commit`.
/// `None` (not an error) means the identity could not be established —
/// exactly the §124 "cannot map confidently" case.
fn find_committed_skill(
    backend: &SystemGitBackend,
    repo: &Path,
    commit: &str,
    skill: &SkillName,
) -> Result<Option<CommittedSkill>> {
    let entries = match backend.tree_recursive(repo, commit, "skills") {
        Ok(entries) => entries,
        // A revision without a readable skills directory has nothing to map.
        Err(_) => return Ok(None),
    };
    if entries.iter().any(|e| e.kind == TreeEntryKind::Gitlink) {
        return Ok(None);
    }
    let mut roots: Vec<String> = Vec::new();
    for entry in &entries {
        if entry.kind != TreeEntryKind::Blob {
            continue;
        }
        let Some(root) = entry.path.strip_suffix(&format!("/{SKILL_FILE}")) else {
            continue;
        };
        if root == "skills" || root.is_empty() {
            continue;
        }
        let (_, leaf) = split_leaf(root);
        if leaf == skill.as_str() {
            roots.push(root.to_owned());
        }
    }
    if roots.len() != 1 {
        return Ok(None);
    }
    let root = roots.into_iter().next().expect("exactly one");
    let prefix = format!("{root}/");
    let mut files = BTreeMap::new();
    for entry in entries
        .iter()
        .filter(|e| e.kind == TreeEntryKind::Blob && e.path.starts_with(&prefix))
    {
        files.insert(
            entry.path[prefix.len()..].to_owned(),
            CommittedFile {
                path: entry.path.clone(),
                executable: entry.is_executable(),
            },
        );
    }
    Ok(Some(CommittedSkill { root, files }))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn adapter_is_derived_from_the_target() {
        assert_eq!(adapter_for(".agents/skills"), Adapter::Agents);
        assert_eq!(adapter_for(".claude/skills"), Adapter::Claude);
        assert_eq!(adapter_for("skills"), Adapter::Custom);
    }

    #[test]
    fn relative_legacy_workspaces_are_rejected() {
        assert!(normalize_workspace("relative/path").is_err());
        assert!(normalize_workspace("/absolute/path").is_ok());
    }

    #[test]
    fn legacy_documents_reject_unsupported_schemas() {
        let root = beskar_test_support::TempRoot::new();
        let profiles = root.path().join("profiles.json");
        std::fs::write(&profiles, r#"{"schema": 9, "profiles": []}"#).expect("write");
        assert!(matches!(
            read_profiles_file(&profiles),
            Err(Error::Schema(_))
        ));
        let registry = root.path().join("registry.json");
        std::fs::write(&registry, r#"{"schema": 2, "installations": []}"#).expect("write");
        assert!(matches!(
            read_registry_file(&registry),
            Err(Error::Schema(_))
        ));
    }

    #[test]
    fn missing_legacy_documents_are_empty_not_fatal() {
        let root = beskar_test_support::TempRoot::new();
        assert!(
            read_profiles_file(&root.path().join("profiles.json"))
                .expect("missing profiles")
                .is_empty()
        );
        assert!(
            read_registry_file(&root.path().join("registry.json"))
                .expect("missing registry")
                .is_empty()
        );
    }

    #[test]
    fn legacy_entry_installed_at_parses_rfc3339() {
        let entry: SkmEntry = serde_json::from_str(
            r#"{"workspace":"/w","target":".agents/skills","profile":"dev",
                "installed_at":"2024-05-01T12:00:00Z"}"#,
        )
        .expect("parse");
        assert!(entry.installed_at.is_some());
        assert_eq!(entry.source_ref, None);
    }
}
