[package]
name = "beskar-cli"
description = "The beskar command line tool."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "beskar_cli"
path = "src/lib.rs"

[[bin]]
name = "beskar"
path = "src/main.rs"

[dependencies]
beskar-core = { path = "../beskar-core" }
bsk = { path = "../bsk" }

[lints]
workspace = true
